#!/bin/bash

set -e

if [[ -z ${TEST_DIR} ]];then
  TEST_DIR=${TEST_VOLUME}/${DELMO_TEST_NAME}
fi
uri=$(cat ${TEST_DIR}/cluster-state.json | jq -r '.leader_uri')

table_name=$1
shift
values=$@

echo "Looking up values in ${table_name}..."

psql ${uri} -c "SELECT * FROM ${table_name};"
