#!/bin/bash

set -e

if [[ -z ${TEST_DIR} ]];then
  TEST_DIR=${TEST_VOLUME}/${DELMO_TEST_NAME}
fi

table_name=$1
value=$2

echo "Checking that ${value} from ${table_name} has replicated..."

cat ${TEST_DIR}/cluster-state.json | jq -r '.uris[]' | while read uri; do
  psql ${uri} -c "SELECT value FROM ${table_name};" | grep "${value}" || {
    echo "Value has not replicated to ${uri}!"
    exit 1
  }
done
