#!/bin/bash

set -e

if [[ -z ${TEST_DIR} ]];then
  TEST_DIR=${TEST_VOLUME}/${DELMO_TEST_NAME}
fi

cached_leader=$(cat ${TEST_DIR}/cluster-state.json | jq -r '.leader_name')

current_leader=$(etcdctl --endpoint "http://${DOCKER_HOST_IP}:4001" get /service/${PATRONI_SCOPE}/leader)

echo "Current leader: ${current_leader}, Previous leader: ${cached_leader}"

[[ $cached_leader != $current_leader ]] || exit 1
