#!/bin/bash

set -e

echo "Deleting all backups for cluster '${PATRONI_SCOPE}'..."
region=$(aws s3api get-bucket-location --bucket ${WAL_S3_BUCKET} | jq -r '.LocationConstraint')
aws s3 --region ${region} rm --recursiv "s3://${WAL_S3_BUCKET}/backups/${PATRONI_SCOPE}"
