#!/bin/bash

set -e

WALE_ENV_DIR=/wal-e/env
mkdir -p ${WALE_ENV_DIR}

echo ${WALE_S3_ENDPOINT} > ${WALE_ENV_DIR}/WALE_S3_ENDPOINT
echo ${AWS_SECRET_ACCESS_KEY} > ${WALE_ENV_DIR}/AWS_SECRET_ACCESS_KEY
echo ${AWS_ACCESS_KEY_ID} > ${WALE_ENV_DIR}/AWS_ACCESS_KEY_ID
echo ${WAL_S3_BUCKET} > ${WALE_ENV_DIR}/WAL_S3_BUCKET
echo "s3://${WAL_S3_BUCKET}/backups/${PATRONI_SCOPE}/wal/" > ${WALE_ENV_DIR}/WALE_S3_PREFIX

echo "Deleting all backups for cluster '${PATRONI_SCOPE}'..."
envdir ${WALE_ENV_DIR} wal-e delete --confirm everything
