#!/bin/bash

set -e

echo "Deleting all backups for cluster '${PATRONI_SCOPE}'..."
region=$(aws s3api get-bucket-location --bucket ${WAL_S3_BUCKET} | jq -r '.LocationConstraint')
if [[ ${region} != 'null' ]]; then
      region_option="--region ${region}"
fi

aws s3 ${region_option} rm --recursiv "s3://${WAL_S3_BUCKET}/backups/${PATRONI_SCOPE}"
