#!/bin/bash

set -e

timestamp_key=$1

if [[ -z ${TEST_DIR} ]];then
  TEST_DIR=${TEST_VOLUME}/${DELMO_TEST_NAME}
fi
leader_name=$(cat ${TEST_DIR}/cluster-state.json | jq -r '.leader_name')

timestamp=$(etcdctl --endpoint "http://${DOCKER_HOST_IP}:4001" get /service/${PATRONI_SCOPE}/store-values-over-time/${timestamp_key})
echo "Restarting from '${timestamp_key}' timestamp: ${timestamp}"

echo ${leader_name}
curl -s http://${DOCKER_HOST_IP}:4001/v2/keys/service/${PATRONI_SCOPE}/members/${leader_name} | jq .

api_url=$(curl -s http://${DOCKER_HOST_IP}:4001/v2/keys/service/${PATRONI_SCOPE}/members/${leader_name} | jq -r ".node.value" | jq -r .api_url)
echo API URL ${api_url}
root_api_url=$(echo ${api_url} | sed -e "s%/patroni$%%")

curl -XPOST ${root_api_url}/restart -d "{\"recovery_target_time\": \"${timestamp}\"}"
