#!/bin/bash

set -e

if [[ -z ${TEST_DIR} ]];then
  TEST_DIR=${TEST_VOLUME}/${DELMO_TEST_NAME}
fi

table_name=$1
value=$2

echo "Storing ${value} in ${table_name}..."

uri=$(cat ${TEST_DIR}/cluster-state.json | jq -r '.leader_uri')

psql ${uri} -c "DROP TABLE IF EXISTS ${table_name};"
psql ${uri} -c "CREATE TABLE ${table_name}(value text);"
psql ${uri} -c "INSERT INTO ${table_name} VALUES ('${value}');"
psql ${uri} -c "SELECT value FROM ${table_name};" | grep "${value}" || {
  echo Could not store and retrieve value in cluster!
  exit 1
}
