#!/bin/bash

set -e

if [[ -z ${TEST_DIR} ]];then
  TEST_DIR=${TEST_VOLUME}/${DELMO_TEST_NAME}
fi

uri=$(cat ${TEST_DIR}/cluster-state.json | jq -r '.leader_uri')

superuser_uri=$(echo ${uri} \
  | sed "s/${APPUSER_USERNAME}/${SUPERUSER_USERNAME}/" \
  | sed "s/${APPUSER_PASSWORD}/${SUPERUSER_PASSWORD}/" )

psql ${superuser_uri} -c "select pg_switch_xlog();"
