meta:
  subnets: (( merge ))
  cfcontainersbroker:
    cc_api_uri: "https://api.10.244.0.34.xip.io"
    external_host: "cf-containers-broker.10.244.0.34.xip.io"
  nats:
    user: nats
    password: nats
    port: 4222
    machines:
      - 10.244.0.6

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  etcd:
    host: 10.244.4.2

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: patroni
    networks:
      - name: patroni1
        static_ips: ~

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: cell_z1
    cloud_properties:
      name: random
    stemcell: (( grab meta.stemcell ))

networks:
- name: patroni1
  type: manual
  subnets: (( grab meta.subnets ))
