#!/bin/bash

set -e

service_name=$1
service_plan=$2
service_instance_name=$3

service_plans_url=$(cf curl /v2/services \
  | jq -r --arg service_name ${service_name} '.resources[] | select(.entity.label == $service_name).entity.service_plans_url')
service_instances_url=$(cf curl ${service_plans_url} \
  | jq -r --arg service_plan ${service_plan} '.resources[] | select(.entity.name == $service_plan).entity.service_instances_url')
cf curl ${service_instances_url} | jq -r --arg instance_name ${service_instance_name} '.resources[] | select(.entity.name == $instance_name).metadata.guid'
